name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: KlaudioEduardo
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualizando a cobrinha"
          git push
